- id: ac4a9f97dc8d47afba2ca580ffb80f17
  alias: Battery - Low battery level detection & notification for all battery sensors
  description: Detect low battery levels and send a notification to discord
  use_blueprint:
    path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      actions:
      - service: notify.discord
        data:
          title: Low Battery Warning
          message: ':zap: {{sensors}} battery is low'
          target:
          - '865449623518969866'
      day: 1
      exclude:
        entity_id:
        - sensor.chirp_battery_level_2
        - sensor.lightcycle_battery_level
