---
################################################################################
# binary_sensor.yaml
# https://www.home-assistant.io/integrations/binary_sensor/
################################################################################

# OpenGarage Sensors
# https://www.home-assistant.io/integrations/opengarage/
- platform: template
  sensors:
    garage_door_occupied:
      friendly_name: "Car in Garage"
      value_template: "{{ states('sensor.og_01_dist') | int < 180 }}"
      availability_template: >-
        {% if is_state('cover.garage_door','closed') %}
          true
        {% else %}
          unavailable
        {% endif %}
      icon_template: >-
        {% if is_state('binary_sensor.garage_door_occupied','on') %}
          mdi:car
        {% else %}
          mdi:car-arrow-right
        {% endif %}
      unique_id: binary_sensor.garage_door_occupied
      delay_on: 5
      delay_off: 5
