# binary_sensor.yaml

#######################################################################################
# Network sensors
#######################################################################################
- platform: ping
  host: !secret network_gw_wan_ip
  name: ping_network_gw_wan_ip_available
  count: 4
  scan_interval: 15
- platform: ping
  host: !secret network_gw_wan_gw
  name: ping_network_gw_wan_gw_available
  count: 4
  scan_interval: 15
- platform: ping
  host: '8.8.8.8'
  name: ping_internet_available
  count: 4
  scan_interval: 15
- platform: ping
  host: !secret network_gw_lan_ip
  name: ping_network_gw_lan_ip_available
  count: 4
  scan_interval: 15
- platform: ping
  host: !secret network_gw_server_ip
  name: ping_network_gw_server_ip_available
  count: 4
  scan_interval: 15
- platform: ping
  host: !secret network_gw_dmz_ip
  name: ping_network_gw_dmz_ip_available
  count: 4
  scan_interval: 15
- platform: ping
  host: !secret network_service_plex
  name: ping_network_service_plex_available
  count: 4
  scan_interval: 15
- platform: ping
  host: !secret network_service_game
  name: ping_network_service_game_available
  count: 4
  scan_interval: 15
- platform: ping
  host: !secret network_service_ad
  name: ping_network_service_ad_available
  count: 4
  scan_interval: 15
- platform: ping
  host: !secret network_service_http
  name: ping_network_service_http_available
  count: 4
  scan_interval: 15
- platform: ping
  host: !secret network_service_puppet
  name: ping_network_service_puppet_available
  count: 4
  scan_interval: 15
- platform: ping
  host: !secret network_service_vmh
  name: ping_network_service_vmh_available
  count: 4
  scan_interval: 15

#######################################################################################
# OpenGarage Sensors
#######################################################################################
- platform: template
  sensors:
    garage_door_occupied:
      friendly_name: "Car in Garage"
      value_template: "{{ states('sensor.og_01_dist') | int < 180 }}"
      availability_template: >-
        {% if is_state('cover.garage_door','closed') %}
          true
        {% else %}
          unavailable
        {% endif %}
      icon_template: >-
        {% if is_state('binary_sensor.garage_door_occupied','on') %}
          mdi:car
        {% else %}
          mdi:car-arrow-right
        {% endif %}
      unique_id: binary_sensor.garage_door_occupied
      delay_on: 5
      delay_off: 5
