# binary_sensor.yaml

#######################################################################################
# Network sensors
#######################################################################################
- platform: ping
  host: !secret network_gw_wan_ip
  name: 'pfsense_wan_available'
  count: 4
  scan_interval: 30
- platform: ping
  host: !secret network_gw_wan_gw
  name: 'pfsense_wan_gw_available'
  count: 4
  scan_interval: 30

#######################################################################################
# PurpleAir Sensors
#######################################################################################
- platform: template
  sensors:
    # Add a connectivity sensor for purpleair. Why isn't the above rest sensor
    # a binary_sensor? Turns out binary_sensor rest devices can't have a
    # json_attributes section.
    purpleair_fremont_available:
      friendly_name: 'PurpleAir Fremont Available'
      unique_id: purpleair_fremont_available
      device_class: connectivity
      value_template: >-
        {% if state_attr('sensor.purpleair_fremont', 'results') != None %}
          {% set stats = state_attr('sensor.purpleair_fremont', 'results')[0]['Stats']|from_json %}
          {% set minutes = stats['timeSinceModified']|int / 1000 /60 %}
          {% if minutes < 5 %}
            true
          {% else %}
            unavailable
          {% endif %}
        {% else %}
          unavailable
        {% endif %}
      availability_template: "{{ states('sensor.purpleair_fremont') != unknown }}"
