---
################################################################################
# lights.yaml
# https://www.home-assistant.io/integrations/light/
################################################################################
# Living Room Lights Group
# https://www.home-assistant.io/integrations/group/#yaml-configuration
- platform: group
  name: "Living Room Lights"
  entities:
    - light.living_room_cabinet_left
    - light.living_room_cabinet_right
    - light.living_room_lamp
