---
################################################################################
# lights.yaml
# https://www.home-assistant.io/integrations/light/
# https://www.home-assistant.io/integrations/group/#yaml-configuration
################################################################################

# Living Room Lights Group
- platform: group
  name: "Living Room Cabinet Lights"
  entities:
    - light.living_room_cabinet_left
    - light.living_room_cabinet_right

# All Floor 1 Lights Group
- platform: group
  name: "Floor 1 Lights"
  entities:
    - light.living_room_lamp
