# sensor.yaml

#######################################################################################
# PurpleAir Sensors
#######################################################################################
# https://community.home-assistant.io/t/purpleair-air-quality-sensor/146588
# Reasonable sensors pulled from https://www.purpleair.com/map
- platform: rest
  name: 'purpleair_home'
  # Substitute in the URL of the sensor you care about. To find the URL, go
  # to purpleair.com/map, find your sensor, click on it, click on "Get This
  # Widget" then click on "JSON".
  resource: !secret purpleair_home_url
  scan_interval: 300
  # Set the sensor value to the last update time of the device.
  device_class: timestamp
  value_template: "{{ value_json.mapVersion }}"
  # The value of the sensor can't be longer than 255 characters, but the
  # attributes can. Store away all the data for use by the templates below.
  json_attributes:
    - mapVersion
    - results
- platform: template
  sensors:
    purpleair_home_aqi:
      friendly_name: 'PurpleAir Home AQI'
      unique_id: purpleair_home_aqi
      # Set this sensor to be the AQI value. Code translated from JavaScript found at:
      # https://docs.google.com/document/d/15ijz94dXJ-YAZLi9iZ_RaBwrZ4KtYeCy08goGBwnbCU/edit#
      value_template: >
        {% if state_attr('sensor.purpleair_home', 'results') != None %}
          {% macro calcAQI(Cp, Ih, Il, BPh, BPl) -%}
            {{ (((Ih - Il)/(BPh - BPl)) * (Cp - BPl) + Il)|round }}
          {%- endmacro %}
          {% set pm25 = state_attr('sensor.purpleair_home', 'results')[0]['PM2_5Value']|float %}
          {% if pm25 > 1000 %}
            invalid
          {% elif pm25 > 350.5 %}
            {{ calcAQI(pm25, 500.0, 401.0, 500.0, 350.5) }}
          {% elif pm25 > 250.5 %}
            {{ calcAQI(pm25, 400.0, 301.0, 350.4, 250.5) }}
          {% elif pm25 > 150.5 %}
            {{ calcAQI(pm25, 300.0, 201.0, 250.4, 150.5) }}
          {% elif pm25 > 55.5 %}
            {{ calcAQI(pm25, 200.0, 151.0, 150.4, 55.5) }}
          {% elif pm25 > 35.5 %}
            {{ calcAQI(pm25, 150.0, 101.0, 55.4, 35.5) }}
          {% elif pm25 > 12.1 %}
            {{ calcAQI(pm25, 100.0, 51.0, 35.4, 12.1) }}
          {% elif pm25 >= 0.0 %}
            {{ calcAQI(pm25, 50.0, 0.0, 12.0, 0.0) }}
          {% else %}
            invalid
          {% endif %}
        {% else %}
          invalid
        {% endif %}
      unit_of_measurement: "AQI"
      availability_template: "{{ is_state('binary_sensor.purpleair_home_available', 'on') }}"
    purpleair_home_description:
      friendly_name: 'PurpleAir Home AQI Description'
      unique_id: purpleair_home_description
      value_template: >
        {% set aqi = states('sensor.purpleair_home_aqi')|float %}
        {% if aqi >= 401.0 %}
          Very Hazardous
        {% elif aqi >= 301.0 %}
          Hazardous
        {% elif aqi >= 201.0 %}
          Very Unhealthy
        {% elif aqi >= 151.0 %}
          Unhealthy
        {% elif aqi >= 101.0 %}
          Unhealthy for Sensitive Groups
        {% elif aqi >= 51.0 %}
          Moderate
        {% elif aqi >= 0.0 %}
          Good
        {% else %}
          undefined
        {% endif %}
      availability_template: "{{ is_state('binary_sensor.purpleair_home_available', 'on') }}"
    purpleair_home_pm25:
      friendly_name: 'PurpleAir Home PM 2.5'
      unique_id: purpleair_home_pm25
      value_template: >-
        {% if state_attr('sensor.purpleair_home', 'results') != None %}
          {{ state_attr('sensor.purpleair_home', 'results')[0]['PM2_5Value'] }}
        {% else %}
          0
        {% endif %}
      unit_of_measurement: "Î¼g/m3"
      availability_template: "{{ is_state('binary_sensor.purpleair_home_available', 'on') }}"
    purpleair_home_temperature:
      friendly_name: 'PurpleAir Home Temperature'
      unique_id: purpleair_home_temperature
      # Why "- 8"?
      # https://www2.purpleair.com/community/faq#!hc-primary-and-secondary-data-header
      value_template: >-
        {% if state_attr('sensor.purpleair_home', 'results') != None %}
          {{ state_attr('sensor.purpleair_home', 'results')[0]['temp_f'] | float - 8 }}
        {% else %}
          0
        {% endif %}
      unit_of_measurement: "Â°F"
      device_class: temperature
      availability_template: "{{ is_state('binary_sensor.purpleair_home_available', 'on') }}"
    purpleair_home_humidity:
      friendly_name: 'PurpleAir Home Humidity'
      unique_id: purpleair_home_humidity
      value_template: >-
        {% if state_attr('sensor.purpleair_home', 'results') != None %}
          {{ state_attr('sensor.purpleair_home', 'results')[0]['humidity'] }}
        {% else %}
          0
        {% endif %}
      unit_of_measurement: "%"
      device_class: humidity
      availability_template: "{{ is_state('binary_sensor.purpleair_home_available', 'on') }}"
    purpleair_home_pressure:
      friendly_name: 'PurpleAir Home Pressure'
      unique_id: purpleair_home_pressure
      value_template: >-
        {% if state_attr('sensor.purpleair_home', 'results') != None %}
          {{ state_attr('sensor.purpleair_home', 'results')[0]['pressure'] }}
        {% else %}
          0
        {% endif %}
      unit_of_measurement: "mb"
      device_class: pressure
      availability_template: "{{ is_state('binary_sensor.purpleair_home_available', 'on') }}"
